# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KJGZPPfyZnyMPaYfamQgZXzLDPNf0Ce

# Выбор сценария и уникального задания

Датасет: Данные о поведении покупателей в мультибрендовом магазине

https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store

3. Прогнозирование спроса

    Цель: прогнозирование спроса на продукты

    Требования:

      *   Ежедневный прогноз готов к 6:00 утра
      *   Точность (MAPE) < 15%
      *   Интеграция с внешними данными
      *   Реализовать интерпретируемость модели (6 пункт)

# Часть 1: Прототипирование и выбор модели
"""

# Часть 1: Настройка окружения и установка библиотек
print("=" * 50)
print("НАСТРОЙКА ОКРУЖЕНИЯ")
print("=" * 50)

!pip install kagglehub mlflow scikit-learn xgboost lightgbm plotly seaborn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Импорт ML-библиотек
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
import xgboost as xgb
import lightgbm as lgb

# Настройка MLflow
import mlflow
import mlflow.sklearn
mlflow.set_experiment("ecommerce_demand_forecasting")

# Часть 2: Загрузка и подготовка датасета
import kagglehub
import pandas as pd
import numpy as np
import os
from pathlib import Path
import matplotlib.pyplot as plt
from io import StringIO

print("=" * 50)
print("ЗАГРУЗКА ДАТАСЕТА")
print("=" * 50)

# Загрузка датасета
path_date = kagglehub.dataset_download("mkechinov/ecommerce-behavior-data-from-multi-category-store")
print("Датасет загружен в:", path_date)

# Поиск файлов
files = list(Path(path_date).glob('*.csv'))
print("Найденные файлы:")
for file in files:
    print(f"- {file.name}")

if files:
    # Выбираем файл за октябрь 2019 для прототипирования
    oct_file = next((f for f in files if '2019-Oct' in f.name), files[0])
    print(f"\nИспользуем файл: {oct_file.name}")

    # Получаем общий размер файла
    original_size_mb = os.path.getsize(oct_file) / 1024**2
    print(f"Размер исходного CSV файла: {original_size_mb:.2f} МБ")

    # Читаем первые несколько строк для анализа структуры
    df_sample = pd.read_csv(oct_file, nrows=5)
    print("\nСтруктура данных:")
    print(df_sample.head())
    print("\nКолонки:", df_sample.columns.tolist())
    print("\nИнформация о типах данных:")
    print(df_sample.info())

else:
    print("CSV файлы не найдены")
    exit()

# Часть 3: Загрузка данных с оптимизацией памяти
print("=" * 50)
print("ОПТИМИЗИРОВАННАЯ ЗАГРУЗКА ДАННЫХ")
print("=" * 50)

def optimize_data_loading(file_path, sample_fraction=0.05, chunk_size=50000):
    """Загрузка данных с оптимизацией памяти и потоковым сэмплированием"""

    print("Анализ структуры данных...")
    # Анализируем только первые строки для определения структуры
    sample_df = pd.read_csv(file_path, nrows=5000)

    # Определяем оптимальные типы данных
    dtype_optimized = {
        'event_time': 'object',
        'event_type': 'category',
        'product_id': 'int32',
        'category_id': 'int64',
        'category_code': 'category',
        'brand': 'category',
        'price': 'float32',
        'user_id': 'int32',
        'user_session': 'object'
    }

    # Получаем общее количество строк для прогресс-бара
    total_rows = 0
    with open(file_path, 'r') as f:
        total_rows = sum(1 for line in f) - 1  # минус заголовок

    print(f"Всего строк в файле: {total_rows:,}")
    print(f"Целевой размер сэмпла: {int(total_rows * sample_fraction):,} строк")

    # Потоковое чтение и сэмплирование
    sampled_chunks = []
    rows_processed = 0
    sample_every_n = int(1 / sample_fraction)

    print("Потоковая загрузка данных...")
    for chunk in pd.read_csv(file_path, dtype=dtype_optimized, chunksize=chunk_size):
        # Сэмплируем из каждого чанка
        chunk_sample = chunk.sample(frac=sample_fraction, random_state=42)
        sampled_chunks.append(chunk_sample)

        rows_processed += len(chunk)
        progress = (rows_processed / total_rows) * 100
        print(f"Обработано: {rows_processed:,} строк ({progress:.1f}%)")

        # Останавливаемся если набрали достаточно данных
        if len(pd.concat(sampled_chunks, ignore_index=True)) >= total_rows * sample_fraction * 1.1:
            break

    # Объединяем все сэмплы
    df = pd.concat(sampled_chunks, ignore_index=True)

    # Дополнительное сэмплирование до точного размера если нужно
    if len(df) > total_rows * sample_fraction:
        df = df.sample(n=int(total_rows * sample_fraction), random_state=42)

    print(f"Финальный размер датасета: {len(df):,} строк")
    print(f"Использовано памяти: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

    return df

# Альтернативный вариант - загрузка только определенного количества строк
def load_limited_rows(file_path, n_rows=100000):
    """Загрузка ограниченного количества строк"""
    print(f"Загрузка первых {n_rows:,} строк...")

    dtype_optimized = {
        'event_time': 'object',
        'event_type': 'category',
        'product_id': 'int32',
        'category_id': 'int64',
        'category_code': 'category',
        'brand': 'category',
        'price': 'float32',
        'user_id': 'int32',
        'user_session': 'object'
    }

    df = pd.read_csv(file_path, dtype=dtype_optimized, nrows=n_rows)
    print(f"Загружено {len(df):,} строк")
    print(f"Использовано памяти: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

    return df

# Пробуем оба подхода
try:
    print("Попытка 1: Потоковое сэмплирование (5% данных)")
    df = optimize_data_loading(oct_file, sample_fraction=0.05)
except Exception as e:
    print(f"Ошибка при потоковом сэмплировании: {e}")
    print("\nПопытка 2: Загрузка ограниченного количества строк")
    df = load_limited_rows(oct_file, n_rows=50000)

# Часть 4: Первичный анализ данных и EDA
print("=" * 50)
print("ПЕРВИЧНЫЙ АНАЛИЗ ДАННЫХ И EDA")
print("=" * 50)

print("1. ОСНОВНАЯ ИНФОРМАЦИЯ О ДАННЫХ:")
print(f"Размерность данных: {df.shape}")
print(f"Период данных: {df['event_time'].min()} - {df['event_time'].max()}")

print("\n2. ТИПЫ ДАННЫХ:")
print(df.dtypes)

print("\n3. ПРОПУЩЕННЫЕ ЗНАЧЕНИЯ:")
missing_data = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_info = pd.DataFrame({
    'Количество пропусков': missing_data,
    'Процент пропусков': missing_percent
})
print(missing_info[missing_info['Количество пропусков'] > 0])

# Преобразование временной метки
print("\n4. ПРЕОБРАЗОВАНИЕ ВРЕМЕННЫХ МЕТОК...")
df['event_time'] = pd.to_datetime(df['event_time'])
df['date'] = df['event_time'].dt.date
df['day_of_week'] = df['event_time'].dt.dayofweek
df['hour'] = df['event_time'].dt.hour

print("\n5. СТАТИСТИКА ПО СОБЫТИЯМ:")
event_counts = df['event_type'].value_counts()
print(event_counts)

# Визуализации
plt.figure(figsize=(15, 10))

# Распределение событий
plt.subplot(2, 2, 1)
event_counts.plot(kind='bar', color=['skyblue', 'lightcoral', 'lightgreen'])
plt.title('Распределение типов событий')
plt.xlabel('Тип события')
plt.ylabel('Количество')
plt.xticks(rotation=45)

# Распределение по дням недели
plt.subplot(2, 2, 2)
df['day_of_week'].value_counts().sort_index().plot(kind='bar', color='lightblue')
plt.title('Распределение событий по дням недели')
plt.xlabel('День недели (0=Понедельник)')
plt.ylabel('Количество событий')

# Распределение цен (логарифмическая шкала)
plt.subplot(2, 2, 3)
prices = df['price'].dropna()
plt.hist(np.log1p(prices[prices > 0]), bins=50, alpha=0.7, color='orange')
plt.title('Распределение цен (логарифмическая шкала)')
plt.xlabel('log(цена + 1)')
plt.ylabel('Частота')

# Топ-10 брендов
plt.subplot(2, 2, 4)
top_brands = df['brand'].value_counts().head(10)
top_brands.plot(kind='bar', color='lightseagreen')
plt.title('Топ-10 брендов по количеству событий')
plt.xlabel('Бренд')
plt.ylabel('Количество событий')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Часть 5: Анализ временных рядов и подготовка целевой переменной
print("=" * 50)
print("АНАЛИЗ ВРЕМЕННЫХ РЯДОВ И ПОДГОТОВКА ДАННЫХ")
print("=" * 50)

# Анализ ежедневных покупок
daily_purchases = df[df['event_type'] == 'purchase'].groupby('date').size()
daily_views = df[df['event_type'] == 'view'].groupby('date').size()

plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
daily_purchases.plot(color='red', alpha=0.7)
plt.title('Ежедневные покупки')
plt.xlabel('Дата')
plt.ylabel('Количество покупок')
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
daily_views.plot(color='blue', alpha=0.7)
plt.title('Ежедневные просмотры')
plt.xlabel('Дата')
plt.ylabel('Количество просмотров')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(f"Всего уникальных продуктов: {df['product_id'].nunique()}")
print(f"Всего уникальных пользователей: {df['user_id'].nunique()}")
print(f"Всего уникальных категорий: {df['category_id'].nunique()}")

# Часть 6: Создание признаков для прогнозирования спроса
print("=" * 50)
print("СОЗДАНИЕ ПРИЗНАКОВ ДЛЯ ПРОГНОЗИРОВАНИЯ")
print("=" * 50)

def create_demand_dataset(df, target_days=1):
    """Создание dataset для прогнозирования спроса"""

    # Создаем целевую переменную - ежедневный спрос по продуктам
    daily_demand = df[df['event_type'] == 'purchase'].groupby(['date', 'product_id']).size().reset_index()
    daily_demand.columns = ['date', 'product_id', 'demand']

    # Создаем признаки
    features_list = []

    unique_dates = sorted(daily_demand['date'].unique())

    for i, current_date in enumerate(unique_dates[target_days:], target_days):
        # Целевая дата
        target_date = unique_dates[i]
        # Исторические данные для признаков
        historical_start = unique_dates[i-target_days]
        historical_end = unique_dates[i-1]

        # Исторические события за предыдущие дни
        historical_data = df[
            (df['date'] >= historical_start) &
            (df['date'] <= historical_end)
        ]

        # Признаки на уровне продукта
        product_features = historical_data.groupby('product_id').agg({
            'event_type': [
                ('total_events', 'count'),
                ('views', lambda x: (x == 'view').sum()),
                ('cart_adds', lambda x: (x == 'cart').sum())
            ],
            'user_id': [
                ('unique_users', 'nunique')
            ],
            'price': [
                ('avg_price', 'mean'),
                ('price_std', 'std')
            ],
            'user_session': [
                ('unique_sessions', 'nunique')
            ]
        }).reset_index()

        # Упрощаем multi-index колонки
        product_features.columns = ['product_id', 'total_events', 'views', 'cart_adds',
                                  'unique_users', 'avg_price', 'price_std', 'unique_sessions']

        # Признаки времени
        product_features['target_date'] = target_date
        product_features['day_of_week'] = pd.to_datetime(target_date).dayofweek
        product_features['is_weekend'] = 1 if pd.to_datetime(target_date).dayofweek >= 5 else 0

        features_list.append(product_features)

    # Объединяем все признаки
    features_df = pd.concat(features_list, ignore_index=True)

    # Объединяем с целевой переменной
    final_df = pd.merge(
        features_df,
        daily_demand.rename(columns={'date': 'target_date'}),
        on=['target_date', 'product_id'],
        how='left'
    ).fillna(0)  # Заполняем нулями где не было покупок

    return final_df

print("Создание признаков...")
demand_df = create_demand_dataset(df, target_days=1)

print(f"Размер финального dataset: {demand_df.shape}")
print("\nПример данных:")
print(demand_df.head())
print(f"\nЦелевая переменная 'demand':")
print(f"Min: {demand_df['demand'].min()}, Max: {demand_df['demand'].max()}, Mean: {demand_df['demand'].mean():.2f}")

# Часть 7: Сравнение моделей машинного обучения
print("=" * 50)
print("СРАВНЕНИЕ МОДЕЛЕЙ МАШИННОГО ОБУЧЕНИЯ")
print("=" * 50)

# Подготовка данных для обучения
X = demand_df.drop(['target_date', 'product_id', 'demand'], axis=1)
y = demand_df['demand']

# Убедимся, что нет пропущенных значений
print("Проверка пропущенных значений:")
print(X.isnull().sum())

# Заполняем пропуски если есть
X = X.fillna(0)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, shuffle=True
)

print(f"Размер train: {X_train.shape}")
print(f"Размер test: {X_test.shape}")

# Модели для сравнения
models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(n_estimators=50, random_state=42, n_jobs=-1),
    'XGBoost': xgb.XGBRegressor(n_estimators=50, random_state=42, n_jobs=-1),
    'LightGBM': lgb.LGBMRegressor(n_estimators=50, random_state=42, n_jobs=-1)
}

results = []

for name, model in models.items():
    print(f"\nОбучение модели: {name}")

    with mlflow.start_run(run_name=name):
        # Логирование параметров
        mlflow.log_param("model_type", name)
        mlflow.log_param("n_estimators", 50 if hasattr(model, 'n_estimators') else 'N/A')

        # Обучение модели
        start_time = datetime.now()
        model.fit(X_train, y_train)
        training_time = (datetime.now() - start_time).total_seconds()

        # Прогнозирование
        y_pred = model.predict(X_test)

        # Оценка метрик
        mape = mean_absolute_percentage_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        mae = np.mean(np.abs(y_test - y_pred))

        # Логирование метрик
        mlflow.log_metrics({
            "MAPE": mape,
            "RMSE": rmse,
            "MAE": mae,
            "training_time_seconds": training_time
        })

        # Логирование модели
        mlflow.sklearn.log_model(model, f"model_{name.lower().replace(' ', '_')}")

        results.append({
            'Model': name,
            'MAPE': mape,
            'RMSE': rmse,
            'MAE': mae,
            'Training Time (s)': training_time
        })

        print(f"  MAPE: {mape:.4f}, RMSE: {rmse:.4f}, Training Time: {training_time:.2f}s")

# Сравнение результатов
results_df = pd.DataFrame(results)
print("\n" + "="*60)
print("СРАВНЕНИЕ РЕЗУЛЬТАТОВ МОДЕЛЕЙ")
print("="*60)
print(results_df.round(4))

# Часть 8: Создание оптимального пайплайна (ПЕРЕРАБОТАННАЯ ВЕРСИЯ)
print("=" * 50)
print("СОЗДАНИЕ ОПТИМАЛЬНОГО ПАЙПЛАЙНА")
print("=" * 50)

# Импорт недостающей функции
from sklearn.metrics import mean_absolute_error

# Сначала проведем глубокую диагностику данных
print("1. ГЛУБОКАЯ ДИАГНОСТИКА ДАННЫХ:")
print(f"Размер X_train: {X_train.shape}, X_test: {X_test.shape}")
print(f"y_train stats: min={y_train.min()}, max={y_train.max()}, mean={y_train.mean():.4f}, std={y_train.std():.4f}")
print(f"y_test stats: min={y_test.min()}, max={y_test.max()}, mean={y_test.mean():.4f}, std={y_test.std():.4f}")

# Анализ распределения целевой переменной
zero_demand_count = (y_train == 0).sum()
zero_demand_percent = zero_demand_count / len(y_train) * 100
print(f"Количество нулевых значений в y_train: {zero_demand_count} ({zero_demand_percent:.2f}%)")

# Анализ ненулевых значений
non_zero_demand = y_train[y_train > 0]
print(f"Ненулевые значения: min={non_zero_demand.min()}, max={non_zero_demand.max()}, mean={non_zero_demand.mean():.4f}")

# Визуализация распределения
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.hist(y_train, bins=50, alpha=0.7, color='blue', edgecolor='black', log=True)
plt.title('Распределение y_train (логарифмическая шкала)')
plt.xlabel('Demand')
plt.ylabel('Frequency (log)')

plt.subplot(1, 3, 2)
plt.boxplot(non_zero_demand)
plt.title('Boxplot ненулевых значений')
plt.ylabel('Demand')

plt.subplot(1, 3, 3)
# Показать только первые 20 значений для наглядности
y_sample = y_train[:20]
plt.bar(range(len(y_sample)), y_sample)
plt.title('Первые 20 значений y_train')
plt.xlabel('Index')
plt.ylabel('Demand')

plt.tight_layout()
plt.show()

print("\n2. АНАЛИЗ ПРОБЛЕМЫ:")
print("Проблема: 97.17% значений целевой переменной равны 0")
print("Это означает, что мы имеем дело с zero-inflated data")
print("Обычные регрессионные модели не подходят для таких данных!")

# Выбираем лучшую модель на основе MAPE
best_model_name = results_df.loc[results_df['MAPE'].idxmin(), 'Model']
print(f"\n3. ЛУЧШАЯ МОДЕЛЬ ПО РЕЗУЛЬТАТАМ: {best_model_name}")

# ПЕРЕРАБОТАННЫЙ ПОДХОД: Двухэтапная модель для zero-inflated data
print("\n4. РЕАЛИЗАЦИЯ ДВУХЭТАПНОЙ МОДЕЛИ:")

# Этап 1: Классификация - будет ли спрос > 0
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Создаем бинарную целевую переменную
y_train_binary = (y_train > 0).astype(int)
y_test_binary = (y_test > 0).astype(int)

print(f"Распределение бинарной целевой переменной:")
print(f"Train: 0s={np.sum(y_train_binary == 0)}, 1s={np.sum(y_train_binary == 1)}")
print(f"Test: 0s={np.sum(y_test_binary == 0)}, 1s={np.sum(y_test_binary == 1)}")

# Создаем пайплайн для классификации
classifier_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1))
])

print("Обучение классификатора...")
classifier_pipeline.fit(X_train, y_train_binary)

# Предсказание классификатора
y_pred_binary = classifier_pipeline.predict(X_test)
y_pred_proba = classifier_pipeline.predict_proba(X_test)[:, 1]

print("Результаты классификации:")
print(f"Accuracy: {accuracy_score(y_test_binary, y_pred_binary):.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred_binary))

# Этап 2: Регрессия для ненулевых значений
print("\nОбучение регрессора для ненулевых значений...")

# Фильтруем данные для регрессии (только ненулевые значения)
non_zero_mask = y_train > 0
X_train_non_zero = X_train[non_zero_mask]
y_train_non_zero = y_train[non_zero_mask]

print(f"Данных для регрессии: {len(X_train_non_zero)} строк")

if len(X_train_non_zero) > 0:
    # Используем логарифмическое преобразование для стабилизации дисперсии
    y_train_non_zero_log = np.log1p(y_train_non_zero)

    # Пайплайн для регрессии
    regressor_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler()),
        ('regressor', xgb.XGBRegressor(
            n_estimators=100,
            max_depth=6,
            learning_rate=0.1,
            random_state=42,
            n_jobs=-1
        ))
    ])

    regressor_pipeline.fit(X_train_non_zero, y_train_non_zero_log)

    # Комбинированное предсказание
    y_pred_combined = np.zeros(len(X_test))

    # Для каждого тестового примера
    for i in range(len(X_test)):
        if y_pred_binary[i] == 1:  # Если классификатор предсказывает спрос
            features = X_test.iloc[i:i+1]  # Берем одну строку
            pred_log = regressor_pipeline.predict(features)[0]
            y_pred_combined[i] = np.expm1(pred_log)
        else:
            y_pred_combined[i] = 0

    # Оценка комбинированной модели
    final_mape = mean_absolute_percentage_error(y_test, y_pred_combined)
    final_rmse = np.sqrt(mean_squared_error(y_test, y_pred_combined))
    final_mae = mean_absolute_error(y_test, y_pred_combined)

    # Создаем кастомную метрику для zero-inflated data
    def zero_inflated_mape(y_true, y_pred):
        """MAPE который учитывает zero-inflated nature данных"""
        # Для ненулевых значений считаем обычный MAPE
        non_zero_mask = y_true > 0
        if np.sum(non_zero_mask) > 0:
            mape_non_zero = mean_absolute_percentage_error(
                y_true[non_zero_mask],
                y_pred[non_zero_mask]
            )
        else:
            mape_non_zero = 0

        # Для классификации считаем accuracy
        accuracy_binary = accuracy_score(
            (y_true > 0).astype(int),
            (y_pred > 0).astype(int)
        )

        # Комбинированная метрика
        combined_metric = 0.7 * mape_non_zero + 0.3 * (1 - accuracy_binary)
        return combined_metric, mape_non_zero, accuracy_binary

    custom_mape, mape_non_zero, accuracy_binary = zero_inflated_mape(y_test, y_pred_combined)

    print(f"\n5. РЕЗУЛЬТАТЫ ДВУХЭТАПНОЙ МОДЕЛИ:")
    print(f"   MAPE (все данные): {final_mape:.4f}")
    print(f"   MAPE (только ненулевые): {mape_non_zero:.4f}")
    print(f"   Accuracy (бинарная классификация): {accuracy_binary:.4f}")
    print(f"   RMSE: {final_rmse:.4f}")
    print(f"   MAE: {final_mae:.4f}")
    print(f"   Custom MAPE: {custom_mape:.4f}")

    # Визуализация результатов
    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.scatter(y_test, y_pred_combined, alpha=0.5)
    max_val = max(y_test.max(), y_pred_combined.max())
    plt.plot([0, max_val], [0, max_val], 'red', linestyle='--')
    plt.xlabel('Фактические значения')
    plt.ylabel('Предсказанные значения')
    plt.title('Предсказания vs Фактические значения')

    plt.subplot(1, 3, 2)
    error = np.abs(y_test - y_pred_combined)
    plt.hist(error, bins=50, alpha=0.7, color='orange')
    plt.xlabel('Абсолютная ошибка')
    plt.ylabel('Частота')
    plt.title('Распределение ошибок')

    plt.subplot(1, 3, 3)
    # Сравнение распределений
    plt.hist(y_test, bins=50, alpha=0.5, label='Фактические', color='blue')
    plt.hist(y_pred_combined, bins=50, alpha=0.5, label='Предсказанные', color='red')
    plt.xlabel('Demand')
    plt.ylabel('Frequency')
    plt.legend()
    plt.title('Сравнение распределений')

    plt.tight_layout()
    plt.show()

    # Логирование в MLflow
    with mlflow.start_run(run_name="two_stage_model_final"):
        mlflow.log_params({
            "model_type": "Two-Stage (Classification + Regression)",
            "classifier": "RandomForest",
            "regressor": "XGBoost",
            "target_transformation": "log1p for non-zero values"
        })

        mlflow.log_metrics({
            "MAPE_all": final_mape,
            "MAPE_non_zero": mape_non_zero,
            "binary_accuracy": accuracy_binary,
            "RMSE": final_rmse,
            "MAE": final_mae,
            "custom_MAPE": custom_mape
        })

        # Сохраняем обе модели
        mlflow.sklearn.log_model(classifier_pipeline, "classifier")
        mlflow.sklearn.log_model(regressor_pipeline, "regressor")

        print("\n6. ПРОВЕРКА ТРЕБОВАНИЙ:")
        if final_mape < 0.15:
            print("✅ ТРЕБОВАНИЕ ВЫПОЛНЕНО: MAPE < 15%")
        else:
            print("❌ ТРЕБОВАНИЕ НЕ ВЫПОЛНЕНО: MAPE >= 15%")
            print("   Однако учтите, что данные содержат 97% нулей,")
            print("   что делает достижение MAPE < 15% чрезвычайно сложным.")
            print("   Рекомендуется обсудить с заказчиком альтернативные метрики.")

else:
    print("Недостаточно ненулевых значений для обучения регрессора")

"""# Часть 2: Реализация Feature Store"""

# Установка Feast и зависимостей
print("=" * 50)
print("УСТАНОВКА FEAST И ЗАВИСИМОСТЕЙ")
print("=" * 50)

!pip install feast==0.31.0 pyarrow pandas scikit-learn -q

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
from pathlib import Path

# Часть 1: Подготовка данных для Feature Store
print("=" * 50)
print("ПОДГОТОВКА ДАННЫХ ДЛЯ FEATURE STORE")
print("=" * 50)

# Создадим базовые фичи на основе нашего датасета
def prepare_feature_store_data(df):
    """Подготовка данных для Feature Store"""

    # Создаем временные метки
    df['event_timestamp'] = pd.to_datetime(df['event_time'])
    df['created_timestamp'] = datetime.now()

    # Агрегируем данные по продуктам и дням
    product_daily_features = df.groupby(['product_id', pd.Grouper(key='event_timestamp', freq='D')]).agg({
        'event_type': [
            ('total_views', lambda x: (x == 'view').sum()),
            ('total_carts', lambda x: (x == 'cart').sum()),
            ('total_purchases', lambda x: (x == 'purchase').sum())
        ],
        'user_id': [
            ('unique_users', 'nunique')
        ],
        'price': [
            ('avg_price', 'mean'),
            ('price_std', 'std'),
            ('min_price', 'min'),
            ('max_price', 'max')
        ],
        'user_session': [
            ('unique_sessions', 'nunique')
        ]
    }).reset_index()

    # Упрощаем multi-index колонки
    product_daily_features.columns = ['product_id', 'event_timestamp',
                                    'total_views', 'total_carts', 'total_purchases',
                                    'unique_users', 'avg_price', 'price_std',
                                    'min_price', 'max_price', 'unique_sessions']

    # Заполняем пропуски
    product_daily_features = product_daily_features.fillna(0)

    # Добавляем created_timestamp
    product_daily_features['created_timestamp'] = datetime.now()

    # Добавляем лаговые фичи (продажи за предыдущий день)
    product_daily_features = product_daily_features.sort_values(['product_id', 'event_timestamp'])
    product_daily_features['prev_day_purchases'] = product_daily_features.groupby('product_id')['total_purchases'].shift(1)
    product_daily_features['prev_day_views'] = product_daily_features.groupby('product_id')['total_views'].shift(1)

    # Заполняем пропуски в лаговых фичах
    product_daily_features[['prev_day_purchases', 'prev_day_views']] = product_daily_features[['prev_day_purchases', 'prev_day_views']].fillna(0)

    return product_daily_features

# Подготавливаем данные
print("Подготовка фич...")
feature_data = prepare_feature_store_data(df)

print(f"Размер подготовленных данных: {feature_data.shape}")
print("\nПример данных:")
print(feature_data.head())
print(f"\nДиапазон дат: {feature_data['event_timestamp'].min()} - {feature_data['event_timestamp'].max()}")

# Часть 2: Создание проекта Feast
print("=" * 50)
print("СОЗДАНИЕ ПРОЕКТА FEAST")
print("=" * 50)

# Создаем директорию для проекта Feast
feast_repo_path = "demand_forecasting_feast"
os.makedirs(feast_repo_path, exist_ok=True)

# Создаем feature_store.yaml
feature_store_yaml = f"""
project: demand_forecasting
registry: {feast_repo_path}/registry.db
provider: local
online_store:
    path: {feast_repo_path}/online_store.db
entity_key_serialization_version: 2
"""

with open(f"{feast_repo_path}/feature_store.yaml", "w") as f:
    f.write(feature_store_yaml)

print(f"Создан проект Feast в: {feast_repo_path}")

# Часть 3: Определение фич в features.py
print("=" * 50)
print("ОПРЕДЕЛЕНИЕ ФИЧ В FEAST")
print("=" * 50)

# Создаем необходимые директории
os.makedirs(f"{feast_repo_path}/data", exist_ok=True)
print(f"Создана директория: {feast_repo_path}/data")

# Создаем файл features.py с правильным форматированием
features_py_content = '''from datetime import timedelta
from feast import Entity, Feature, FeatureView, ValueType
from feast.data_source import FileSource

# Определение сущности - продукт
product = Entity(
    name="product_id",
    value_type=ValueType.INT64,
    description="Уникальный идентификатор продукта",
)

# Источник данных для продукта
product_stats_source = FileSource(
    path="{path}",  # путь будет заполнен позже
    event_timestamp_column="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# Feature View для ежедневной статистики продуктов
product_daily_stats = FeatureView(
    name="product_daily_stats",
    entities=["product_id"],
    ttl=timedelta(days=7),  # данные актуальны 7 дней
    features=[
        Feature(name="total_views", dtype=ValueType.INT64),
        Feature(name="total_carts", dtype=ValueType.INT64),
        Feature(name="total_purchases", dtype=ValueType.INT64),
        Feature(name="unique_users", dtype=ValueType.INT64),
        Feature(name="avg_price", dtype=ValueType.DOUBLE),
        Feature(name="price_std", dtype=ValueType.DOUBLE),
        Feature(name="min_price", dtype=ValueType.DOUBLE),
        Feature(name="max_price", dtype=ValueType.DOUBLE),
        Feature(name="unique_sessions", dtype=ValueType.INT64),
        Feature(name="prev_day_purchases", dtype=ValueType.INT64),
        Feature(name="prev_day_views", dtype=ValueType.INT64),
    ],
    online=True,
    batch_source=product_stats_source,
    tags={{"team": "demand_forecasting", "type": "daily_stats"}},
)

# Feature View для агрегированной статистики (последние 3 дня)
product_3day_stats = FeatureView(
    name="product_3day_stats",
    entities=["product_id"],
    ttl=timedelta(days=10),
    features=[
        Feature(name="views_3d_avg", dtype=ValueType.DOUBLE),
        Feature(name="purchases_3d_avg", dtype=ValueType.DOUBLE),
        Feature(name="conversion_rate_3d", dtype=ValueType.DOUBLE),
    ],
    online=True,
    batch_source=product_stats_source,  # в реальном проекте был бы отдельный источник
    tags={{"team": "demand_forecasting", "type": "aggregated_stats"}},
)
'''

# Сохраняем данные фич в Parquet файл
feature_data_path = f"{feast_repo_path}/data/product_daily_stats.parquet"
print(f"Сохранение данных в: {feature_data_path}")

try:
    feature_data.to_parquet(feature_data_path, index=False)
    print(f"✅ Данные фич успешно сохранены в: {feature_data_path}")
    print(f"Размер файла: {os.path.getsize(feature_data_path) / 1024**2:.2f} MB")
except Exception as e:
    print(f"❌ Ошибка при сохранении данных: {e}")
    # Создаем демонстрационные данные если основная сохранение не удалось
    demo_data = pd.DataFrame({
        'product_id': [1, 2, 3],
        'event_timestamp': [datetime.now() - timedelta(days=i) for i in range(3)],
        'created_timestamp': [datetime.now()] * 3,
        'total_views': [100, 150, 200],
        'total_purchases': [10, 15, 20],
        'avg_price': [25.5, 30.0, 35.5]
    })
    demo_data.to_parquet(feature_data_path, index=False)
    print(f"✅ Созданы демонстрационные данные в: {feature_data_path}")

# Обновляем путь в features.py с использованием безопасного форматирования
try:
    # Используем замену только конкретного плейсхолдера
    features_py_content_final = features_py_content.replace("{path}", feature_data_path)

    with open(f"{feast_repo_path}/features.py", "w") as f:
        f.write(features_py_content_final)

    print("✅ Файл features.py создан")

except Exception as e:
    print(f"❌ Ошибка при создании features.py: {e}")
    # Альтернативный способ - записать файл без форматирования
    with open(f"{feast_repo_path}/features.py", "w") as f:
        f.write(f'''
from datetime import timedelta
from feast import Entity, Feature, FeatureView, ValueType
from feast.data_source import FileSource

# Определение сущности - продукт
product = Entity(
    name="product_id",
    value_type=ValueType.INT64,
    description="Уникальный идентификатор продукта",
)

# Источник данных для продукта
product_stats_source = FileSource(
    path="{feature_data_path}",
    event_timestamp_column="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# Feature View для ежедневной статистики продуктов
product_daily_stats = FeatureView(
    name="product_daily_stats",
    entities=["product_id"],
    ttl=timedelta(days=7),
    features=[
        Feature(name="total_views", dtype=ValueType.INT64),
        Feature(name="total_carts", dtype=ValueType.INT64),
        Feature(name="total_purchases", dtype=ValueType.INT64),
        Feature(name="unique_users", dtype=ValueType.INT64),
        Feature(name="avg_price", dtype=ValueType.DOUBLE),
        Feature(name="price_std", dtype=ValueType.DOUBLE),
        Feature(name="min_price", dtype=ValueType.DOUBLE),
        Feature(name="max_price", dtype=ValueType.DOUBLE),
        Feature(name="unique_sessions", dtype=ValueType.INT64),
        Feature(name="prev_day_purchases", dtype=ValueType.INT64),
        Feature(name="prev_day_views", dtype=ValueType.INT64),
    ],
    online=True,
    batch_source=product_stats_source,
    tags={{"team": "demand_forecasting", "type": "daily_stats"}},
)

# Feature View для агрегированной статистики
product_3day_stats = FeatureView(
    name="product_3day_stats",
    entities=["product_id"],
    ttl=timedelta(days=10),
    features=[
        Feature(name="views_3d_avg", dtype=ValueType.DOUBLE),
        Feature(name="purchases_3d_avg", dtype=ValueType.DOUBLE),
        Feature(name="conversion_rate_3d", dtype=ValueType.DOUBLE),
    ],
    online=True,
    batch_source=product_stats_source,
    tags={{"team": "demand_forecasting", "type": "aggregated_stats"}},
)
''')
    print("✅ Файл features.py создан (альтернативный метод)")

# Проверяем что файлы созданы
print("\n📁 ПРОВЕРКА СОЗДАННЫХ ФАЙЛОВ:")
created_files = [
    f"{feast_repo_path}/feature_store.yaml",
    f"{feast_repo_path}/features.py",
    f"{feast_repo_path}/data/product_daily_stats.parquet"
]

for file_path in created_files:
    if os.path.exists(file_path):
        file_size = os.path.getsize(file_path) / 1024  # KB
        print(f"✅ {file_path} ({file_size:.1f} KB)")
    else:
        print(f"❌ {file_path} - не найден")

# Дополнительно: читаем и проверяем содержимое features.py
print("\n📝 СОДЕРЖИМОЕ features.py:")
try:
    with open(f"{feast_repo_path}/features.py", "r") as f:
        content = f.read()
        print("Первые 10 строк файла:")
        lines = content.split('\n')[:10]
        for i, line in enumerate(lines, 1):
            print(f"{i:2d}: {line}")
except Exception as e:
    print(f"❌ Не удалось прочитать features.py: {e}")

# Часть 4: Инициализация и применение Feature Store
print("=" * 50)
print("ИНИЦИАЛИЗАЦИЯ FEATURE STORE")
print("=" * 50)

try:
    from feast import FeatureStore

    # Инициализация Feature Store
    store = FeatureStore(repo_path=feast_repo_path)

    # Применяем определения фич
    print("Применение определений фич...")

    # Импортируем определения из features.py
    import importlib.util
    import sys

    # Динамически импортируем features.py
    spec = importlib.util.spec_from_file_location("features", f"{feast_repo_path}/features.py")
    features_module = importlib.util.module_from_spec(spec)
    sys.modules["features"] = features_module
    spec.loader.exec_module(features_module)

    # Получаем объекты из модуля
    product = features_module.product
    product_daily_stats = features_module.product_daily_stats
    product_3day_stats = features_module.product_3day_stats

    # Применяем фичи
    store.apply([product, product_daily_stats, product_3day_stats])

    print("✅ Feature Store инициализирован!")
    print(f"Доступные Feature Views: {[fv.name for fv in store.list_feature_views()]}")
    print(f"Доступные Entities: {[e.name for e in store.list_entities()]}")

except Exception as e:
    print(f"❌ Ошибка при инициализации Feature Store: {e}")
    print("Создаем демонстрационный Feature Store...")

    # Демонстрационный код для случая ошибки
    class DemoFeatureStore:
        def __init__(self):
            self.feature_views = ["product_daily_stats", "product_3day_stats"]
            self.entities = ["product_id"]

        def list_feature_views(self):
            class FeatureView:
                def __init__(self, name):
                    self.name = name
            return [FeatureView(fv) for fv in self.feature_views]

        def list_entities(self):
            class Entity:
                def __init__(self, name):
                    self.name = name
            return [Entity(e) for e in self.entities]

        def get_historical_features(self, entity_df, features):
            class Result:
                def to_df(self):
                    # Возвращаем демонстрационные данные
                    demo_df = entity_df.copy()
                    for feature in features:
                        feature_name = feature.split(":")[1] if ":" in feature else feature
                        if "views" in feature_name:
                            demo_df[feature_name] = np.random.randint(50, 200, len(entity_df))
                        elif "purchases" in feature_name:
                            demo_df[feature_name] = np.random.randint(0, 10, len(entity_df))
                        elif "price" in feature_name:
                            demo_df[feature_name] = np.random.uniform(20, 100, len(entity_df))
                        else:
                            demo_df[feature_name] = np.random.randint(10, 50, len(entity_df))
                    return demo_df
            return Result()

        def get_online_features(self, features, entity_rows):
            class Result:
                def to_dict(self):
                    result = {}
                    for feature in features:
                        feature_name = feature.split(":")[1] if ":" in feature else feature
                        result[feature_name] = [np.random.randint(50, 200)]
                    result['product_id'] = [entity_rows[0]['product_id']]
                    return result
            return Result()

    store = DemoFeatureStore()
    print("✅ Демонстрационный Feature Store создан")

"""# ВАРИАНТ 2"""

# Установите PyArrow отдельно, перед установкой Feast
!pip install "pyarrow>=14.0.0"

# Установка правильной версии Feast
print("=" * 50)
print("УСТАНОВКА FEAST")
print("=" * 50)

# Попробуем несколько версий, так как некоторые могут иметь проблемы с зависимостями
try:
    # Сначала попробуем установить стабильную версию
    !pip install feast==0.31.0 -q
    print("✅ Feast 0.31.0 установлен успешно")
except Exception as e:
    print(f"❌ Ошибка при установке Feast 0.31.0: {e}")
    try:
        # Альтернативная версия
        !pip install feast==0.40.1 -q
        print("✅ Feast 0.40.1 установлен успешно")
    except Exception as e2:
        print(f"❌ Ошибка при установке Feast 0.40.1: {e2}")
        # Последняя стабильная версия
        !pip install feast -q
        print("✅ Установлена последняя версия Feast")

# Проверим установку
try:
    import feast
    print(f"✅ Feast успешно импортирован, версия: {feast.__version__}")
except ImportError as e:
    print(f"❌ Ошибка импорта Feast: {e}")

"""# Часть 3: Интеграция с MLflow"""



"""# Часть 4: Инференс в production"""



"""# Часть 5: Мониторинг данных и моделей"""



"""# Часть 6: Сравнение стратегий обучения"""



"""# Часть 7: Реализация уникального требования"""

